accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import welcome, login,logout, register, profile, user_info

app_name = 'accounts'  #  'accounts' namespace
urlpatterns = [
    path('', welcome, name = 'welcome'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('user_info/', user_info, name='user_info'),
    path('profile/', profile, name='profile'),
]

community/urls.py
from django.urls import path
from .views import  home, create_post

app_name = 'community'  #  'community' namespace
urlpatterns = [
    path('home/', home, name='home'),
    path('post/create/', create_post, name='create_post'),
]

ishema/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('community/', include('community.urls')),
    path('opportunity/', include('opportunities.urls')),
    path('dashboard/', include('dashboard.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

opportunities/urls.py
from django.urls import path
from .views import create_opportunity, opportunity_detail, apply_for_opportunity, opportunity_list, donate, urgent_cause, process_donation, donation_success, search_organizations

app_name = 'opportunity'
urlpatterns = [
  path('create/',create_opportunity, name="create_opportunity" ),
  path('detail/<int:pk>/',opportunity_detail, name="opportunity_detail" ),
  path('apply/<int:pk>',apply_for_opportunity, name="apply_for_opportunity" ),
  path('list/',opportunity_list, name="opportunity_list" ),
  path('donate/',donate, name="donate" ),
  path('donate/<int:organization_id>/',donate, name="donate" ),
  path('urgent/',urgent_cause, name="urgent_cause" ),
  path('process-donation/', process_donation, name='process_donation'),
  path('donation-success/', donation_success, name='donation_success'),
  path('search/', search_organizations, name='search_organizations'),
]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.core.files.storage import default_storage
from opportunities.models import Organization

"""UserProfile model extends the default Django User model"""
class UserProfile(models.Model):
    USER_ROLE_CHOICES = (
        ('volunteer', 'Volunteer'),
        ('organization', 'Organization'),
    )
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True, null=True)
    skills = models.CharField(max_length=255, blank=True, null=True)
    interests = models.CharField(max_length=255, blank=True, null=True)
    profile_picture = models.ImageField(upload_to='profile_pictures/', default='profile_pictures/default-profile.png', blank=True, null=True, storage=default_storage)
    role = models.CharField(max_length=12, choices=USER_ROLE_CHOICES)
    organization = models.ForeignKey(Organization, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.user.username

    """This will allow you to access the organizations a user follows like this: request.user.userprofile.followed_organizations"""
    @property
    def followed_organizations(self):
        return Organization.objects.filter(organizationfollow__user=self.user)



# Automatically create or update UserProfile when a User is created or updated
@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
    instance.userprofile.save()

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm, SetPasswordForm






# class UserProfileForm(forms.ModelForm):
#     class Meta:
#         model = UserProfile
#         fields = ['bio', 'skills', 'interests', 'profile_picture', 'role']
#         widgets = {
#             'bio': forms.Textarea(attrs={'placeholder': 'Tell us about yourself', 'rows': 3}),
#             'skills': forms.TextInput(attrs={'placeholder': 'Your skills'}),
#             'interests': forms.TextInput(attrs={'placeholder': 'Your interests'}),
#             'profile_picture': forms.FileInput(),
#             'role': forms.Select(choices=UserProfile.USER_ROLE_CHOICES),
#         }
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['bio', 'skills', 'interests', 'profile_picture', 'role']
        widgets = {
            'bio': forms.Textarea(attrs={
                'placeholder': 'Share a bit about yourself',
                'rows': 4,
                'class': 'form-control rounded',
                'style': 'resize:none;'
            }),
            'skills': forms.TextInput(attrs={
                'placeholder': 'Enter your skills',
                'class': 'form-control rounded'
            }),
            'interests': forms.TextInput(attrs={
                'placeholder': 'List your interests',
                'class': 'form-control rounded'
            }),
            'profile_picture': forms.FileInput(attrs={
                'class': 'form-control-file'
            }),
            'role': forms.Select(attrs={
                'class': 'form-select rounded'
            }),
        }
        labels = {
            'bio': 'About You',
            'skills': 'Your Skills',
            'interests': 'Your Interests',
            'profile_picture': 'Profile Picture',
            'role': 'Role',
        }



class LoginForm(AuthenticationForm):
    """Customized login form with styles for username and password fields."""
    
    username = forms.CharField(
        widget=forms.TextInput(attrs={
            'autofocus': True,
            'placeholder': 'Username',
            'class': 'form-control',
            'style': 'border: 1px solid #007bff; padding: 10px; border-radius: 5px;',
        })
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Password',
            'class': 'form-control',
            'style': 'border: 1px solid #007bff; padding: 10px; border-radius: 5px;',
        })
    )




class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    role = forms.ChoiceField(choices=UserProfile.USER_ROLE_CHOICES)
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password']
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
            UserProfile.objects.create(user=user, role=self.cleaned_data['role'])
        return user
    

class SignUpForm(UserCreationForm):
     email = forms.EmailField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Email Address'}))
     first_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'First Name'}))
     last_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Last Name'}))



     class Meta:
            model = User
            fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

            def __init__(self, *args, **kwargs):
                 super(SignUpForm, self).__init__(*args, **kwargs)
                 self.fields['username'].widget.attrs['class'] = 'form-control'
                 self.fields['username'].widget.attrs['placeholder'] = 'User Name'
                 self.fields['username'].label = ''
                 self.fields['username'].help_text = '<span class="form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></span>'

                 self.fields['password1'].widget.attrs['class'] = 'form-control'
                 self.fields['password1'].widget.attrs['placeholder'] = 'Password'
                 self.fields['password1'].label = ''
                 self.fields['password1'].help_text = '<ul class="form-text text-muted small"><li>Your password can\'t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can\'t be a commonly used password.</li><li>Your password can\'t be entirely numeric.</li></ul>'

                 self.fields['password2'].widget.attrs['class'] = 'form-control'
                 self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
                 self.fields['password2'].label = ''
                 self.fields['password2'].help_text = '<span class="form-text text-muted"><small>Enter the same password as before, for verification.</small></span>'



class UserInfoForm(forms.ModelForm):
    bio = forms.CharField(
        label="", 
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Type bio'}),
        required=False
    )
    skills = forms.CharField(
        label="", 
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'List skills'}),
        required=False
    )
    interests = forms.CharField(
        label="", 
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Interest'}),
        required=False
    )
    profile_picture = forms.ImageField(
        label="Edit Profile Picture", 
        required=False
    )
    role = forms.ChoiceField(
        choices=UserProfile.USER_ROLE_CHOICES, 
        label="Select Your Role", 
        widget=forms.Select(attrs={'class': 'form-control', 'placeholder': 'Select role'}),
        required=False
    )

    class Meta:
        model = UserProfile
        fields = ('bio', 'skills', 'interests', 'profile_picture', 'role')

accounts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .forms import SignUpForm, UserProfileForm, LoginForm, UserInfoForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib import messages
from .models import UserProfile
from opportunities.models import Opportunity

def welcome(request):
    opportunities = Opportunity.objects.order_by('-date')[:3]

    context = {
        'range': range(3),
        'opportunities': opportunities
    }
    return render(request, 'accounts/welcome.html', context)


def user_info(request):
    user_profile=request.user.userprofile
    if request.user.is_authenticated:
      #find profile whose user id is [user ID]
      current_user = UserProfile.objects.get(user__id = request.user.id)
      form = UserInfoForm(request.POST or None, instance = current_user)
      
      if form.is_valid():
        form.save()
        messages.success(request, ("Profile Info Updated Successfully!!"))
        return redirect('accounts:user_info')
      return render(request, 'accounts/user_info.html', {'form': form, 'user_profile':user_profile})
    else:
      messages.success(request, ("You must be logged in to view that page"))
      return redirect('accounts:welcome')
    





def login(request):
    if request.method == 'POST':
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth_login(request, user)
                return redirect('community:home')  # Redirect to home or another page after login
            else:
                form.add_error(None, 'Invalid username or password')
    else:
        form = LoginForm()

    return render(request, 'accounts/login.html', {'form': form})



def logout(request):
    if request.method == 'POST':
        auth_logout(request)
        request.session.flush()  # This clears the session data
        return redirect('accounts:welcome')
    else:
        return redirect('accounts:welcome')




def register(request):
    user_form = SignUpForm()
    if request.method == 'POST':
        user_form = SignUpForm(request.POST)
        if user_form.is_valid():
            # Create and save the user
            user_form.save()

            username = user_form.cleaned_data['username']
            password = user_form.cleaned_data['password1']
            
            # Authenticate the user
            user = authenticate(username=username, password=password)
            
            # Check if authentication was successful
            if user is not None:
                # Log in the user
                auth_login(request, user)
                messages.success(request, "Fill out the personal info section")
                return redirect('accounts:user_info')
            else:
                messages.error(request, "There was a problem logging in after registration.")
                return redirect('accounts:register')
        else:
            messages.error(request, "Whoops! There was a problem registering the user. Try again.")
            return redirect('accounts:register')
    else:
        return render(request, 'accounts/register.html', {'user_form': user_form})




# Remove or comment out @login_required for development
# @login_required
def profile(request):
    user_profile = request.user.userprofile
    # if not request.user.is_authenticated:
    #     # Handle anonymous users during development
    #     return redirect('profile')  # Redirect to home page or show a message

    if request.method == 'POST':
        profile_form = UserProfileForm(request.POST, request.FILES, instance=request.user.userprofile)
        if profile_form.is_valid():
            profile_form.save()
            return redirect('accounts:profile')
    else:
        profile_form = UserProfileForm(instance=request.user.userprofile)

    return render(request, 'accounts/profile.html', {'profile_form': profile_form, 'user_profile':user_profile})

accounts/templates/accounts/login.html
{% extends 'welcome_base.html' %}
<!-- Content -->
{% block content %}
<div class="row justify-content-center align-items-center vh-100">
  <div class="col-md-5">
    <div class="card">
      <div class="card-body">
        <h2>Login</h2>
        <form method="post">
          {% csrf_token %} {{ form.as_p }}
          <button type="submit" class="btn btn-secondary">Login</button>
        </form>
        <p>
          Don't have an account?
          <a href="{% url 'accounts:register' %}">Register here</a>
        </p>
      </div>
    </div>
  </div>
</div>

{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base_min.html' %}
{% load static %}
<!-- horizontal nav -->
{% block nav_menu %}
<div class="navbar navbar-light bg-white border-bottom">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">IshemaLogo</a>

    <!-- Navigation-center -->
    <div class="navbar-center navbar-light bg-light">
      <div class="container">
        <ul class="navbar-center-list">
          <li class="navbar-center-item">
            <button class="navbar-center-link active" href="#home">Self</button>
          </li>
          <li class="navbar-center-item">
            <button class="navbar-center-link" href="#about">Community</button>
          </li>
        </ul>
      </div>
    </div>

    <form class="d-flex">
      <input
        class="form-control me-2"
        type="search"
        placeholder="Search "
        aria-label="Search"
      />
      <button class="btn btn-outline-primary" type="submit">Search</button>
    </form>
  </div>
</div>
{% endblock %}

<!-- block  side nav menu -->
{% block left_navigation %}
<!-- Custon navigation menu for home -->
{% include 'accounts/profile_overview.html' %}

<ul class="nav flex-column">
  <!--  Home is default left nav menu -->
  <li class="nav-item">
    <a class="nav-link active" href="{% url 'community:home' %}"
      ><i class="bi bi-house-door-fill"></i> Home</a
    >
  </li>

  <li class="nav-item"></li>
    <a class="nav-link" href="{% url 'accounts:profile' %}"
      ><i class="bi bi-person-circle"></i> Profile</a
    >
  </li>

  <li class="nav-item">
    <a class="nav-link" href="{% url 'accounts:user_info' %}"
      ><i class="bi bi-card-list"></i> Personal Information</a
    >
  </li>
</ul>
{% endblock %}

<!-- block main content -->
{% block feeds %}
<div class="container mt-5 d-flex justify-content-center">
      <div class="col-md-10">
        <div class="card">
          <div class="card-body">
            <h2>Profile</h2>
            <form method="post" enctype="multipart/form-data">
             {% csrf_token %}
             {{ profile_form.as_p }}
            <button type="submit" class=" btn btn-info">Update Profile</button>
          </form>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

accounts/templates/accounts/profile_overview.html
{% if user.is_authenticated %}
<div class="profile-container">
  <!-- Profile Icon -->
  <div class="profile-icon" id="profileIcon">
     <div class="user_header">
      <img
      src="{% if user_profile.profile_picture %}{{ user_profile.profile_picture.url }}{% else %}/static/assets/images/default-profile.png{% endif %}"
      alt="Profile Image"
      class="profile-img"
    />
      <div class="user-name">
          <strong>{{ user_profile.user.username }} </strong>
      </div>
     </div>
  </div>

  <!-- Profile Card -->
  <div class="profile-card border border-info" id="profileCard">
    <button type="button" class="btn-close" id="close_btn" aria-label="Close"></button>
    <div class="profile-details">
      
      <!-- User Header: Profile Picture and Name -->
      <div class="user_header">
        <img
      src="{% if user_profile.profile_picture %}{{ user_profile.profile_picture.url }}{% else %}/static/assets/images/default-profile.png{% endif %}"
      alt="Profile Image"
      class="profile-img"
    />
        <h3>{{ user_profile.user.first_name }}</h3>
      </div>

      <!-- Volunteer Hours Overview Section -->
      <div class="hours_overview">
        <div>
          <p><strong>Volunteer Hours</strong></p>
          <p><span>x</span><small> Hours Volunteered</small></p>
        </div>

        <!-- Log Hours Button -->
        <div class="view_btn">
          <button class="btn btn-secondary">Log Hours</button>
        </div>
      </div>

      <!-- Divider Line -->
      <hr />

      <!-- Upcoming Deeds List -->
      <ul style="list-style: none;">
          <li class="nav-item">
              <a class="nav-link" href="{% url 'opportunity:opportunity_list' %}"><i class="bi bi-calendar-event-fill"></i> Upcoming Deeds</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:profile' %}"><i class="bi bi-person-circle"></i> Profile</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="#"><i class="bi bi-gear-fill"></i> Settings</a>
          </li>
          <li class="nav-item">
              <a class="nav-link logout-btn" href="{% url 'accounts:logout' %}"><i class="bi bi-box-arrow-right"></i> Logout</a>
          </li>
      </ul>
      
    </div>
  </div>
</div>
{% else %}
<!-- Optional: You can add a message or a link to the login page here -->
<p>Please <a href="{% url 'accounts:login' %}">log in</a> to view your profile.</p>
{% endif %}

accounts/templates/accounts/register.html
{% extends 'welcome_base.html' %} 
<!-- Content -->
{% block content %}
<div class="row justify-content-center align-items-center vh-100">

  <div class="col-md-5">
    <div class="card">
      <div class="card-body">
        <h2>Register</h2>

        <form method="post" enctype="multipart/form-data">
          {% csrf_token %} 
          {{ user_form.as_p }} 
          {{ profile_form.as_p }}
          <button type="submit" class="btn btn-secondary">Register</button>
        </form>
        <p>
          Already have an account?
          <a href="{% url 'accounts:login' %}">Login here</a>
        </p>
      </div>
    </div>
  </div>
</div>

{% endblock %}

accounts/templates/accounts/user_info.html
{% extends 'base_min.html' %}
{% load static %}
<!-- horizontal nav -->
{% block nav_menu %}
<div class="navbar navbar-light bg-white border-bottom">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">IshemaLogo</a>

    <!-- Navigation-center -->
    <div class="navbar-center navbar-light bg-light">
      <div class="container">
        <ul class="navbar-center-list">
          <li class="navbar-center-item">
            <button class="navbar-center-link active" href="#home">Self</button>
          </li>
          <li class="navbar-center-item">
            <button class="navbar-center-link" href="#about">Community</button>
          </li>
        </ul>
      </div>
    </div>

    <form class="d-flex">
      <input
        class="form-control me-2"
        type="search"
        placeholder="Search "
        aria-label="Search"
      />
      <button class="btn btn-outline-primary" type="submit">Search</button>
    </form>
  </div>
</div>
{% endblock %}

<!-- block  side nav menu -->
{% block left_navigation %}
<!-- Custon navigation menu for home -->
{% include 'accounts/profile_overview.html' %}

<ul class="nav flex-column">
  <!--  Home is default left nav menu -->
  <li class="nav-item">
    <a class="nav-link active" href="{% url 'community:home' %}"
      ><i class="bi bi-house-door-fill"></i> Home</a
    >
  </li>

  <li class="nav-item">
    <a class="nav-link" href="{% url 'opportunity:donate' %}"
      ><i class="bi bi-cash-stack"></i> Donate</a
    >
  </li>
</ul>
{% endblock %}

<!-- block main content -->
{% block feeds %}
<div class="container mt-5 d-flex justify-content-center">
      <div class="col-md-10">
        <div class="card">
          <div class="card-body">
            <h1 class="text-center mt-5 mb-5">Personal Address Information</h1>
        <form method="post" action="{% url 'accounts:user_info' %}">
          {% csrf_token %}
          {{ form.as_p }}
          <br>
          <button type="submit" class="btn btn-secondary ">Save Profile</button>
        </form>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

accounts/templates/accounts/welcome_footer.html
<footer class="footer-container mt-5">
      <div class="container p-4">
        <div class="row">
          <!-- Contact Information -->
          <div class="col-lg-4 col-md-6 mb-4 mb-md-0">
            <h5 class="text-uppercase">Contact Us</h5>
            <ul class="list-unstyled">
              <li><i class="icon bi bi-house-door"></i>Kigali, Rwanda</li>
              <li><i class="icon bi bi-envelope"></i> info@volunteerapp.com</li>
            </ul>
          </div>

          <!-- Quick Links -->
          <div class="col-lg-4 col-md-6 mb-4 mb-md-0">
            <h5 class="text-uppercase">Quick Links</h5>
            <ul class="list-footer">
              <li>
                <a href="#home" class="text-light footer-link"
                  > Home</a
                >
              </li>
              <li>
                <a href="#about" class="text-light footer-link"
                  > About</a
                >
              </li>
              <li>
                <a href="#opportunities" class="text-light footer-link"
                  >Opportunities</a
                >
              </li>
              <li>
                <a href="#login" class="text-light footer-link"
                  >Login</a
                >
              </li>
              <li>
                <a href="#signup" class="text-light footer-link"
                  >Sign up</a
                >
              </li>
            </ul>
          </div>

          <!-- Social Media -->
          <div class="col-lg-4 col-md-12 mb-4 mb-md-0">
            <h5 class="text-uppercase">Follow Us</h5>
            <a href="https://facebook.com" class="me-3 footer-link social-link"
              ><i class="icon bi bi-facebook"></i
            >Facebook</a>
            <a href="https://twitter.com" class="me-3 footer-link social-link"
              ><i class="icon bi bi-twitter"></i
            >X Post</a>
            <a href="https://instagram.com" class="me-3 footer-link social-link"
              ><i class="icon bi bi-instagram"></i
            >Instagram</a>
            <a href="https://linkedin.com" class="footer-link social-link"
              ><i class="icon bi bi-linkedin"></i
            >LinkedIn</a>
          </div>
        </div>
      </div>

      <!-- Footer Bottom -->
      <div class="text-center p-3">
        <p class="mb-0">
          © 2024 Ishema: Community Volunteering App. All rights reserved.
        </p>
      </div>
    </footer>

accounts/templates/accounts/welcome_nav.html
<!-- Header / Navigation -->
    <nav class="navbar-container ">
      <h3>IshemaLogo</h3>
      <div class="nav-bar">
      <div class="container">
        <ul class="navbar-list">
          <li class="navbar-item">
            <a class="navbar-link active" href="{% url 'accounts:welcome' %}">Home</a>
          </li>
          <li class="navbar-item">
            <a class="navbar-link" href="#about">About</a>
          </li>
          <li class="navbar-item">
            <a class="navbar-link" href="#opportunities">
              Opportunities
            </a>
          </li>
          <li class="navbar-item"></li>
            <a class="navbar-link" href="#blogs">
              Blogs
            </a>
          </li>
          <li class="navbar-item">
            <a class="navbar-link" href="{% url 'accounts:login' %}">Login</a>
          </li>
          <li class="navbar-item">
            <a class="navbar-link" href="{% url 'accounts:register' %}">Sign up</a>
          </li>
        </ul>
      </div>
      </div>
    </nav>
    